In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("employee.csv")

In [3]:
df.head()

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
0,101,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0
1,102,Priya Sharma,28.0,Data Science,85000.0,Noida,2021-03-10,5,priya@gmail.com,"Python,R,Power BI",Ankit,4.8,8000.0
2,103,Rahul Verma,31.0,Web,72000.0,Gurgaon,2020-01-20,7,rahul@gmail.com,"React,NodeJS",Rohit,4.2,6000.0
3,104,Simran Kaur,NaN,AI,69000.0,Delhi,2023-02-01,1,simran@gmail.com,"Python,TensorFlow",Rohit,4.0,NaN
4,105,Arjun Mehta,27.0,Data Science,NaN,Noida,2021-07-19,4,arjun@gmail.com,"SQL,Excel",Ankit,3.9,4500.0

In [4]:
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Salary', 'City',
       'JoiningDate', 'Experience', 'Email', 'Skills', 'Manager',
       'Performance', 'Bonus'],
      dtype='object')

In [5]:
list(df.columns)

['EmployeeID',
 'Name',
 'Age',
 'Department',
 'Salary',
 'City',
 'JoiningDate',
 'Experience',
 'Email',
 'Skills',
 'Manager',
 'Performance',
 'Bonus']

In [6]:
for col in df.columns:
    print(col)

EmployeeID
Name
Age
Department
Salary
City
JoiningDate
Experience
Email
Skills
Manager
Performance
Bonus

In [7]:
df.isnull().count()

EmployeeID     12
Name           12
Age            12
Department     12
Salary         12
City           12
JoiningDate    12
Experience     12
Email          12
Skills         12
Manager        12
Performance    12
Bonus          12
dtype: int64

In [8]:
type(df.columns)

pandas.core.indexes.base.Index

In [9]:
column_s=df.select_dtypes(include=["string","int"])
column_s

    EmployeeID  Experience
0          101           2
1          102           5
2          103           7
3          104           1
4          105           4
5          106           1
6          107           6
7          108           3
8          109           6
9          110          10
10         111           2
11         112           0

In [10]:
print(column_s.columns.tolist())

['EmployeeID', 'Experience']

In [11]:
df.select_dtypes(include=["object"])

,Name,Department,City,JoiningDate,Email,Skills,Manager
0,Aman Singh,AI,Delhi,2022-06-15,aman@gmail.com,"Python,SQL",Rohit
1,Priya Sharma,Data Science,Noida,2021-03-10,priya@gmail.com,"Python,R,Power BI",Ankit
2,Rahul Verma,Web,Gurgaon,2020-01-20,rahul@gmail.com,"React,NodeJS",Rohit
3,Simran Kaur,AI,Delhi,2023-02-01,simran@gmail.com,"Python,TensorFlow",Rohit
4,Arjun Mehta,Data Science,Noida,2021-07-19,arjun@gmail.com,"SQL,Excel",Ankit
5,Neha Gupta,HR,Delhi,2024-01-10,neha@gmail.com,"Communication,Excel",Pooja
6,Karan Malhotra,AI,Pune,2019-09-25,karan@gmail.com,"Python,PyTorch,Docker",Rohit
7,Riya Kapoor,Finance,Mumbai,2022-11-05,riya@gmail.com,"Excel,Tally",Mehul
8,Anjali Sharma,Web,Gurgaon,2020-05-18,anjali@gmail.com,"HTML,CSS,JavaScript",Rohit
9,Vikram Singh,Management,Delhi,2017-08-30,NaN,Leadership,Amit
10,Aman Singh,AI,Delhi,2022-06-15,aman@gmail.com,"Python,SQL",Rohit
11,Mehak Arora,Intern,Noida,2025-01-15,mehak@gmail.com,Python,Ankit

In [12]:
df.iloc[1:9,1:3]

             Name   Age
1    Priya Sharma  28.0
2     Rahul Verma  31.0
3     Simran Kaur   NaN
4     Arjun Mehta  27.0
5      Neha Gupta  25.0
6  Karan Malhotra  29.0
7     Riya Kapoor  26.0
8   Anjali Sharma  30.0

In [13]:
df.loc["Aman Singh":"Priya Sharma"]

Empty DataFrame
Columns: [EmployeeID, Name, Age, Department, Salary, City, JoiningDate, Experience, Email, Skills, Manager, Performance, Bonus]
Index: []

In [14]:
df.head()

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
0,101,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0
1,102,Priya Sharma,28.0,Data Science,85000.0,Noida,2021-03-10,5,priya@gmail.com,"Python,R,Power BI",Ankit,4.8,8000.0
2,103,Rahul Verma,31.0,Web,72000.0,Gurgaon,2020-01-20,7,rahul@gmail.com,"React,NodeJS",Rohit,4.2,6000.0
3,104,Simran Kaur,NaN,AI,69000.0,Delhi,2023-02-01,1,simran@gmail.com,"Python,TensorFlow",Rohit,4.0,NaN
4,105,Arjun Mehta,27.0,Data Science,NaN,Noida,2021-07-19,4,arjun@gmail.com,"SQL,Excel",Ankit,3.9,4500.0

In [15]:
df[df["City"]=="Delhi"]

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
0,101,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0
3,104,Simran Kaur,NaN,AI,69000.0,Delhi,2023-02-01,1,simran@gmail.com,"Python,TensorFlow",Rohit,4.0,NaN
5,106,Neha Gupta,25.0,HR,48000.0,Delhi,2024-01-10,1,neha@gmail.com,"Communication,Excel",Pooja,4.1,3000.0
9,110,Vikram Singh,35.0,Management,120000.0,Delhi,2017-08-30,10,NaN,Leadership,Amit,4.7,15000.0
10,111,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0

In [16]:
df.isna().sum()

EmployeeID     0
Name           0
Age            1
Department     0
Salary         1
City           0
JoiningDate    0
Experience     0
Email          1
Skills         0
Manager        0
Performance    0
Bonus          1
dtype: int64

In [17]:
df[df.duplicated()]

Empty DataFrame
Columns: [EmployeeID, Name, Age, Department, Salary, City, JoiningDate, Experience, Email, Skills, Manager, Performance, Bonus]
Index: []

In [18]:
df.nsmallest(3,"Age")

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
11,112,Mehak Arora,23.0,Intern,25000.0,Noida,2025-01-15,0,mehak@gmail.com,Python,Ankit,3.7,1000.0
0,101,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0
10,111,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0

In [19]:
df.shape

(12, 13)

In [20]:
df.shape[0]

12

In [21]:
df.head()

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
0,101,Aman Singh,24.0,AI,65000.0,Delhi,2022-06-15,2,aman@gmail.com,"Python,SQL",Rohit,4.5,5000.0
1,102,Priya Sharma,28.0,Data Science,85000.0,Noida,2021-03-10,5,priya@gmail.com,"Python,R,Power BI",Ankit,4.8,8000.0
2,103,Rahul Verma,31.0,Web,72000.0,Gurgaon,2020-01-20,7,rahul@gmail.com,"React,NodeJS",Rohit,4.2,6000.0
3,104,Simran Kaur,NaN,AI,69000.0,Delhi,2023-02-01,1,simran@gmail.com,"Python,TensorFlow",Rohit,4.0,NaN
4,105,Arjun Mehta,27.0,Data Science,NaN,Noida,2021-07-19,4,arjun@gmail.com,"SQL,Excel",Ankit,3.9,4500.0

In [22]:
df["Name"]

0         Aman Singh
1       Priya Sharma
2        Rahul Verma
3        Simran Kaur
4        Arjun Mehta
5         Neha Gupta
6     Karan Malhotra
7        Riya Kapoor
8      Anjali Sharma
9       Vikram Singh
10        Aman Singh
11       Mehak Arora
Name: Name, dtype: object

In [23]:
df.loc[df["Salary"]>70,["Name","Age"]]

              Name   Age
0       Aman Singh  24.0
1     Priya Sharma  28.0
2      Rahul Verma  31.0
3      Simran Kaur   NaN
5       Neha Gupta  25.0
6   Karan Malhotra  29.0
7      Riya Kapoor  26.0
8    Anjali Sharma  30.0
9     Vikram Singh  35.0
10      Aman Singh  24.0
11     Mehak Arora  23.0

In [31]:

df[df.isna().any(axis=1)]

,EmployeeID,Name,Age,Department,Salary,City,JoiningDate,Experience,Email,Skills,Manager,Performance,Bonus
3,104,Simran Kaur,NaN,AI,69000.0,Delhi,2023-02-01,1,simran@gmail.com,"Python,TensorFlow",Rohit,4.0,NaN
4,105,Arjun Mehta,27.0,Data Science,NaN,Noida,2021-07-19,4,arjun@gmail.com,"SQL,Excel",Ankit,3.9,4500.0
9,110,Vikram Singh,35.0,Management,120000.0,Delhi,2017-08-30,10,NaN,Leadership,Amit,4.7,15000.0

In [ ]:
df.loc("EmployeeID")